# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name                  = "tfstate"
    disable_dependency_optimization = true
    key                             = "./terraform.tfstate"
    resource_group_name             = "terraform"
    storage_account_name            = "willpxxr"
  }
}
