name: Terraform

on:
  pull_request:
    branches:
      - main

env:
  TERRAFORM_VERSION: 1.1.3
  TERRAGRUNT_VERSION: 0.31.3

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          sudo mv ./terraform /usr/local/bin
          rm -rf terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - name: Install Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64
          chmod +x ./terragrunt_linux_amd64
          sudo mv ./terragrunt_linux_amd64 /usr/local/bin/terragrunt
      - name: Terragrunt
        env:
          ARM_TENANT_ID: f96bf61a-8913-4999-9e1d-eff3a996f979
          ARM_SUBSCRIPTION_ID: a653fcc5-5b9c-4d8e-820d-7cd61fb8c3d8
          ARM_CLIENT_ID: 7e278bb3-6f57-40c4-ad50-04ba578f89bf
          ARM_CLIENT_SECRET: ${{secrets.TERRAFORM_CLIENT_SECRET}}
        run: |
          terragrunt run-all init
          terragrunt run-all plan
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'TODO: terraform plan output'
            })
